import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { motion, Variants } from "framer-motion";
import { useState } from "react";
import NavBar from "@/Components/misc/navbar/navBar";
import { Entry } from "@/Components/pages/initial/entry";
import { Services } from "@/Components/pages/initial/services";
import { Footer } from "@/Components/misc/footer/footer";
import { Team } from "@/Components/pages/initial/team";
import { About } from "@/Components/pages/initial/about";
import { FabBtn } from "@/Components/misc/buttonFab/fab";
import { Articles } from "@/Components/pages/initial/articles";
import { Contact } from "@/Components/pages/initial/contact";
import { Faq } from "@/Components/pages/initial/faq";

const itemVariants: Variants = {
  open: {
    opacity: 1,
    y: 0,
    transition: { type: "spring", stiffness: 300, damping: 24 },
  },
  closed: { opacity: 0, y: 20, transition: { duration: 0.2 } },
};

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);
  return (
    <>
      <Head>
        <title>Geniüs ⭐ Advocacia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col bg-gray-200 justify-end-end">
        <NavBar />
        <FabBtn />
        <Entry />
        <About />
        <Team />
        <Contact />
        {/* <Articles />
        <Faq /> */}
        <Footer />
      </div>
    </>
  );
}
